#!/bin/sh

pacman -Qqe >/tmp/currently_installed_packages.txt

MAX=${1:-10}

grep "\[ALPM\] installed" /var/log/pacman.log |
	grep -F -f /tmp/currently_installed_packages.txt |
	tail -n "$MAX" |
	sed -e 's/\[ALPM\] installed //' -e 's/(.*$//'

rm /tmp/currently_installed_packages.txt
