#!/bin/sh

theme="$HOME/.config/rofi/main_without_icons.rasi"

get_options() {
	echo "󱖑 Toggle"
	echo "󰒭 Next"
	echo "󰒮 Previous"
	echo "󰝙 Shuffle"
	echo "󱢮 Random Album"
	echo "󰝚 Repeat"
	echo "󰽯 Which"
	echo "󰝛 Mute"
	echo " Volume Down"
	echo " Volume Up"
	echo "󰘏 Player"
	echo " Play: Type to search"
	echo " Stop"
}

main() {
	choice=$(get_options | rofi -dmenu -i -fuzzy -p "" -theme "$theme" -selected-row 0)

	case "$choice" in
	*Toggle)
		mpc toggle
		[ "$(mpc status | grep -o 'playing')" = "playing" ] && songinfo
		;;
	*Next)
		mpc next
		;;
	*Previous)
		mpc prev
		;;
	*Shuffle)
		mpc clear
		mpc listall | shuf -n 8 | mpc add
		mpc next
		mpc play
		;;
	*Album)
		mpc find album "$(mpc list album | shuf -n 1)" | mpc add
		mpc next
		mpc play
		;;
	*Which)
		songinfo
		;;
	*Player)
		kitty -e ncmpcpp
		;;
	*Play:*)
		search_query=$(echo "$choice" | sed 's/Play: //')
		best_match=$(mpc listall | fzf -f "$search_query" | tail -n 1)
		echo "$best_match"
		mpc add "$best_match"
		mpc play "$(mpc playlist | wc -l)"
		;;
	*Down)
		amixer -q sset Master 13%-
		;;
	*Up)
		amixer -q sset Master 13%+
		;;
	*Mute)
		mpc volume 0
		;;
	*Repeat)
		mpc repeat
		;;
	*Stop)
		mpc stop
		;;
	*)
		exit 0
		;;
	esac

	set -e
}

main &

exit 0
