#!/bin/sh

for d in /sys/class/power_supply/*; do
  [ -d "$d" ] || continue
  if [ -f "$d/capacity_level" ]; then
    CAP=$(cat "$d/capacity_level")
    DEVICE=$(cat "$d/model_name")
    echo "$DEVICE: $CAP"
  fi
done
