#!/usr/bin/env bash

Cover=/tmp/cover.png
bkpCover=~/.config/ncmpcpp/assets/fallback.webp
mpddir=~/Music

current_track="$(mpc current -f %file%)"

if [ -n "$current_track" ]; then
	ffmpeg -i "$mpddir/$current_track" "${Cover}" -y &>/dev/null || cp $bkpCover $Cover
	dunstify --replace=27072 -i /tmp/cover.png "Playing.." "$(mpc --format '%title% \n%artist%' current)"
fi
