#!/bin/sh

DIR="${1:-.}"

SUDO="$( [ "$(stat -c %U "$DIR")" = "root" ] && echo 'sudo ' || echo '' )"

FILE=$(${SUDO}rg --files --hidden $DIR | ${SUDO}fzf --preview="bat {}" --bind="ctrl-space:toggle-preview" --preview-window=:hidden)
[[ -z "$FILE" ]] || ${SUDO}nvim "$FILE"
